<a href="https://colab.research.google.com/github/Ape108/Quantum_Portfolio_Optimization/blob/main/general_qubo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# QUBO - Quadratic Unconstrained Binary Optimization


*Example Values*

In [ ]:
import numpy as np

size = 5
features = np.array([1,0,0,1,1]) # x^T vector
weights = np.triu(np.array([ # Upper Triangular Matrix Q
    [ 0.5, -1.0,  0.2, -0.8,  1.5],
    [-1.0,  0.3, -0.5,  1.0, -0.2],
    [ 0.2, -0.5, -0.1,  0.6, -1.1],
    [-0.8,  1.0,  0.6,  0.9,  0.4],
    [ 1.5, -0.2, -1.1,  0.4, -0.7]
    ]))


### Summation Form (General)<br>
## $E(\mathbf{x}) = \sum_{i=1}^{n} Q_{ii}x_i + \sum_{i=1}^{n-1}\sum_{j=i+1}^{n} Q_{ij}x_i x_j$


In [ ]:
def get_cost_summation_form(weights, features, size):
  # Summation Form
  linear_sum = 0
  for i in range(size):
    Q_ii = weights[i][i]
    x_i = features[i]
    linear_sum += (Q_ii * x_i)

  quadratic_sum = 0
  for j in range(size):
    for i in range(j):
      Q_ij = weights[i][j]
      x_i = features[i]
      x_j = features[j]
      quadratic_sum += (Q_ij * x_i * x_j)

  energy_cost = linear_sum + quadratic_sum

  print("linear_sum + quadratic_sum = energy_cost")
  print(f"{linear_sum} + {quadratic_sum} = {energy_cost:.2f}")

get_cost_summation_form(weights, features, size)

linear_sum + quadratic_sum = energy_cost
0.7 + 1.1 = 1.80


### Matrix Form (General)<br>
## $E(\mathbf{x}) = \mathbf{x}^\top Q \mathbf{x}$


In [ ]:
def get_cost_matrix_form(weights, features):
  x_T = features
  Q = weights
  x = features.T

  energy_cost = x_T @ Q @ x

  print("x_T @ Q @ x = energy_cost")
  print(f"{x_T} @ \n{Q} @ \n{x}^T \n= {energy_cost:.2f}")

get_cost_matrix_form(weights, features)


x_T @ Q @ x = energy_cost
[1 0 0 1 1] @ 
[[ 0.5 -1.   0.2 -0.8  1.5]
 [ 0.   0.3 -0.5  1.  -0.2]
 [ 0.   0.  -0.1  0.6 -1.1]
 [ 0.   0.   0.   0.9  0.4]
 [ 0.   0.   0.   0.  -0.7]] @ 
[1 0 0 1 1]^T 
= 1.80
